image: dart:stable
stages:
- build
- deploy
build:
stage: build
script:
  - apt-get update && apt-get install -y curl unzip
  - curl -s https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.10.5-sta… | tar -xJf -
  - export PATH="$PATH:`pwd`/flutter/bin"
  - flutter doctor
  - flutter pub get
  - flutter build web --release
artifacts:
  paths:
  - build/web
pages:
stage: deploy
script:
  - mv build/web public
artifacts:
  paths:
  - public